### ISSUE TITLE
Switch to Markdown

### ISSUE THREAD

**Issue by IvanFon** [OCESS/SpacesimWebsite#4]
Does anyone think switching every page to use Markdown would be a good idea? It wouldn't be difficult to implement, and while some HTML formatting could be lost, it would be very easy to edit.

**Comment by pmelanson** [comment]
seems like the contact and the join us pages are what would not be converted, correct? Otherwise, we're not using any special HTML formatting it looks like.

**Comment by Porso7** [comment]
Yeah. I guess every other page could use Markdown. I'll change it some time this week.

**Comment by pmelanson** [comment]
10/10 maintainability

**Comment by IvanFon** [comment]
All pages are now using Makdown.
