### ISSUE TITLE
Change the wiki link

### ISSUE THREAD

**Issue by Pika3323** [OCESS/SpacesimWebsite#7]
Make the link for the wiki (in the header) link *straight* to the wiki. "Click here to go to.." pages are a bit of a nuisance.

**Comment by Porso7** [comment]
Due to a suggestion by Jarde, we no longer have a wiki link in the header.  This was changed by commit [c3e16bf](https://github.com/OCESS/SpacesimWebsite/commit/c3e16bfebcd07423d180e15a33642152f864d0bd) to the develop branch.
